#!/bin/bash
#
# small script to fix pyaarlo imports while testing hass-aarlo

sed -i.old -e 's@from custom_components.aarlo.pyaarlo@from pyaarlo@' *py
sed -i.old -e 's@import custom_components.aarlo.pyaarlo@import pyaarlo@' *py
