DOORBELL_DEVICE_01 = {
    'allowedMqttTopics': ['d/XXXXXX-XXXX-XXX-XXXXXXXXX/out/doorbells/YYYYYYYYYYYYY/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/wifi/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/subscriptions/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/audioPlayback/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/modes/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/basestation/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/siren/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/devices/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/storage/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/schedule/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/diagnostics/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/automationRevisionUpdate/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/audio/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/activeAutomations/#',
                          'd/XXXXXX-XXXX-XXX-XXXXXXXXX/out/lte/#'],
    'automationRevision': 1,
    'connectivity': {'connected': True,
                     'mepStatus': 'unknown',
                     'signalStrength': '3',
                     'type': 'wifi'},
    'dateCreated': 1675520680490,
    'deviceId': 'YYYYYYYYYYYYY',
    'deviceName': 'Front Door Bell',
    'deviceType': 'doorbell',
    'displayOrder': 1,
    'interfaceSchemaVer': '6',
    'interfaceVersion': 'i002',
    'lastImageUploaded': 'true',
    'lastModified': 1741094584950,
    'mediaObjectCount': 33,
    'modelId': 'AVD2001A',
    'owner': {'firstName': 'Sssss',
              'lastName': 'Hhhhhhh',
              'ownerId': 'OOOOOOO-OOO-OOOOOOO'},
    'parentId': 'YYYYYYYYYYYYY',
    'presignedFullFrameSnapshotUrl': 'https://arlos3-prod-z2.arlo.com/SNAPSHOT.JPG',
    'presignedLastImageUrl': 'https://arlolastimage-z2.arlo.com/LASTIMAGE.JPG',
    'presignedSnapshotUrl': 'https://arlos3-prod-z2.arlo.com/PSNAPSHOT.JPG',
    'properties': {'activityState': 'idle',
                   'antiFlicker': {'autoDefault': 1, 'mode': 0},
                   'apiVersion': 1,
                   'audioDetected': False,
                   'autoLowPowerMode': {'enabled': False, 'threshold': 20},
                   'automationPaused': False,
                   'batteryLevel': 51,
                   'batteryTech': 'Rechargeable',
                   'brightness': 0,
                   'callLedEnable': False,
                   'chargeNotificationLedEnable': True,
                   'chargeOnly': False,
                   'chargerTech': 'None',
                   'chargingState': 'Off',
                   'chimes': {'ZZZZZZZZZZZZZ': {'trackId': '11a7bcbe-a078-41d3-ad81-c65840a0571c',
                                                'volume': 90}},
                   'claimed': True,
                   'connectionState': 'available',
                   'connectivity': [{'connected': True,
                                     'ipAddr': '192.168.1.123',
                                     'signalStrength': 3,
                                     'ssid': 'hinterland',
                                     'type': 'wifi',
                                     'wifiRssi': -41}],
                   'continuousStreamState': 'inactive',
                   'flip': False,
                   'groups': [{'camera': 'YYYYYYYYYYYYY',
                               'chimes': ['ZZZZZZZZZZZZZ', 'traditionalChime'],
                               'doorbell': 'YYYYYYYYYYYYY',
                               'id': 'YYYYYYYYYYYYY',
                               'type': 'doorbell'}],
                   'hasStreamed': True,
                   'hdr': 'off',
                   'hwVersion': 'AVD2001Aer1.4',
                   'idleLedEnable': False,
                   'inclusion': False,
                   'interfaceVersion': 8,
                   'liveFeed': True,
                   'lowBattery': False,
                   'mic': {'mute': False, 'volume': 100},
                   'mirror': False,
                   'modelId': 'AVD2001A',
                   'motion': {'zones': []},
                   'motionDetected': False,
                   'motionSetupModeEnabled': False,
                   'motionSetupModeSensitivity': 80,
                   'mqttSupport': False,
                   'nightVisionMode': 1,
                   'notificationsBlocked': False,
                   'olsonTimeZone': 'America/Bogota',
                   'pirLedEnable': True,
                   'powerSaveMode': 0,
                   'privacy': {'zones': []},
                   'privacyActive': False,
                   'privacyShutterState': True,
                   'privacyShutterTestMode': False,
                   'resolution': {'height': 1536, 'width': 1536},
                   'resources': [{'ID': 1,
                                  'duration': 0,
                                  'pattern': 'alert',
                                  'sirenState': 'off',
                                  'sirenTimestamp': 0,
                                  'sirenType': 'PCM',
                                  'type': 'siren',
                                  'volume': 8}],
                   'serialNumber': 'YYYYYYYYYYYYY',
                   'setupActive': False,
                   'signalStrength': 3,
                   'silentMode': {'active': False,
                                  'call': True,
                                  'chimes': {'ZZZZZZZZZZZZZ': True,
                                             'traditionalChime': True}},
                   'sipCallActive': False,
                   'smartTracking': False,
                   'smartZoom': {'bottomrightx': 0,
                                 'bottomrighty': 0,
                                 'topleftx': 0,
                                 'toplefty': 0},
                   'speaker': {'mute': False, 'volume': 100},
                   'state': 'idle',
                   'streamingMode': 'eventBased',
                   'swVersion': '1.9.1.0_8_9eedd22_ceefa49',
                   'timeSynchState': 'synchronized',
                   'timeZone': 'COT5',
                   'traditionalChime': False,
                   'traditionalChimeDuration': 320,
                   'traditionalChimeType': 'none',
                   'updateAvailable': None,
                   'updateCountryCode': 'unknown',
                   'videoMode': 'wide',
                   'voiceMailEnabled': False,
                   'zoom': {'bottomrightx': 1536,
                            'bottomrighty': 1536,
                            'topleftx': 0,
                            'toplefty': 0}},
    'state': 'provisioned',
    'states': {'activeMode': 'mode0', 'override': False, 'schemaVersion': 1},
    'uniqueId': 'IIIIIII-III-IIIIIII_IIIIIIIIIIIII',
    'userId': 'UUUU-UUU-UUUUUUUU',
    'userRole': 'ADMIN',
    'xCloudId': 'XXXXXX-XXXX-XXX-XXXXXXXXX'
}
