
BASE_STATION_02 = {
    'allowedMqttTopics': ['d/BASE-STATION-02-XCLOUD-ID/out/basestation/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/wifi/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/subscriptions/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/audioPlayback/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/modes/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/basestation/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/siren/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/devices/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/storage/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/schedule/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/diagnostics/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/automationRevisionUpdate/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/audio/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/activeAutomations/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/lte/#'],
    'automationRevision': 6245,
    'connectivity': {'connected': True,
                     'mepStatus': 'unknown',
                     'type': 'ethernet'},
    'dateCreated': 1485909784398,
    'deviceId': 'BASE-STATION-02-ID',
    'deviceName': 'Rear Base',
    'deviceType': 'basestation',
    'displayOrder': 2,
    'firmwareVersion': '1.21.0.3_1545_2417bfb',
    'interfaceSchemaVer': '15',
    'interfaceVersion': 'i017',
    'lastModified': 1741143721863,
    'mediaObjectCount': 0,
    'modelId': 'VMB3010',
    'owner': {'firstName': 'OWNER-NAME',
              'lastName': 'OWNER-LAST-NAME',
              'ownerId': 'OWNER-ID'},
    'properties': {},
    'state': 'provisioned',
    'uniqueId': 'BASE-STATION-02-UNIQUE-ID',
    'userId': 'USER-ID',
    'userRole': 'ADMIN',
    'xCloudId': 'BASE-STATION-02-XCLOUD-ID'
}

DOOR_BELL_01 = {
    'allowedMqttTopics': ['d/DOOR-BELL-01-XCLOUD-ID/out/doorbells/DOOR-BELL-01-ID/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/wifi/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/subscriptions/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/audioPlayback/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/modes/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/basestation/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/siren/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/devices/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/storage/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/schedule/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/diagnostics/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/automationRevisionUpdate/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/audio/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/activeAutomations/#',
                          'd/DOOR-BELL-01-XCLOUD-ID/out/lte/#'],
    'automationRevision': 1,
    'connectivity': {'connected': True,
                     'mepStatus': 'unknown',
                     'signalStrength': '3',
                     'type': 'wifi'},
    'dateCreated': 1675520680490,
    'deviceId': 'DOOR-BELL-01-ID',
    'deviceName': 'Door Bell 01',
    'deviceType': 'doorbell',
    'displayOrder': 1,
    'interfaceSchemaVer': '6',
    'interfaceVersion': 'i002',
    'lastImageUploaded': 'true',
    'lastModified': 1741143722713,
    'mediaObjectCount': 35,
    'modelId': 'AVD2001A',
    'owner': {'firstName': 'USER-NAME',
              'lastName': 'USER-LAST-NAME',
              'ownerId': 'OWNER-ID'},
    'parentId': 'DOOR-BELL-01-ID',
    'presignedFullFrameSnapshotUrl': 'https://arlos3-prod-z2.arlo.com/c091c33a_d750_4561_8557_5b250f5491e1/OWNER-ID/DOOR-BELL-01-ID/fullFrameSnapshot.jpg',
    'presignedLastImageUrl': 'https://arlos3-prod-z2.arlo.com/c091c33a_d750_4561_8557_5b250f5491e1/OWNER-ID/DOOR-BELL-01-ID/recordings/1741128803693_thumb.jpg',
    'presignedSnapshotUrl': 'https://arlos3-prod-z2.arlo.com/c091c33a_d750_4561_8557_5b250f5491e1/OWNER-ID/DOOR-BELL-01-ID/snapshot.jpg',
    'properties': {'activityState': 'idle',
                   'antiFlicker': {'autoDefault': 1, 'mode': 0},
                   'apiVersion': 1,
                   'audioDetected': False,
                   'autoLowPowerMode': {'enabled': False,
                                        'threshold': 20},
                   'automationPaused': False,
                   'batteryLevel': 51,
                   'batteryTech': 'Rechargeable',
                   'brightness': 0,
                   'callLedEnable': False,
                   'chargeNotificationLedEnable': True,
                   'chargeOnly': False,
                   'chargerTech': 'None',
                   'chargingState': 'Off',
                   'chimes': {'CHIME-01-ID': {'trackId': '11a7bcbe-a078-41d3-ad81-c65840a0571c',
                                              'volume': 90}},
                   'claimed': True,
                   'connectionState': 'available',
                   'connectivity': [{'connected': True,
                                     'ipAddr': '192.168.1.123',
                                     'signalStrength': 3,
                                     'ssid': 'hinterland',
                                     'type': 'wifi',
                                     'wifiRssi': -41}],
                   'continuousStreamState': 'inactive',
                   'flip': False,
                   'groups': [{'camera': 'DOOR-BELL-01-ID',
                               'chimes': ['CHIME-01-ID',
                                          'traditionalChime'],
                               'doorbell': 'DOOR-BELL-01-ID',
                               'id': 'DOOR-BELL-01-ID',
                               'type': 'doorbell'}],
                   'hasStreamed': True,
                   'hdr': 'off',
                   'hwVersion': 'AVD2001Aer1.4',
                   'idleLedEnable': False,
                   'inclusion': False,
                   'interfaceVersion': 8,
                   'liveFeed': True,
                   'lowBattery': False,
                   'mic': {'mute': False, 'volume': 100},
                   'mirror': False,
                   'modelId': 'AVD2001A',
                   'motion': {'zones': []},
                   'motionDetected': False,
                   'motionSetupModeEnabled': False,
                   'motionSetupModeSensitivity': 80,
                   'mqttSupport': False,
                   'nightVisionMode': 1,
                   'notificationsBlocked': False,
                   'olsonTimeZone': 'America/Bogota',
                   'pirLedEnable': True,
                   'powerSaveMode': 0,
                   'privacy': {'zones': []},
                   'privacyActive': False,
                   'privacyShutterState': True,
                   'privacyShutterTestMode': False,
                   'resolution': {'height': 1536, 'width': 1536},
                   'resources': [{'ID': 1,
                                  'duration': 0,
                                  'pattern': 'alert',
                                  'sirenState': 'off',
                                  'sirenTimestamp': 0,
                                  'sirenType': 'PCM',
                                  'type': 'siren',
                                  'volume': 8}],
                   'serialNumber': 'DOOR-BELL-01-ID',
                   'setupActive': False,
                   'signalStrength': 3,
                   'silentMode': {'active': False,
                                  'call': True,
                                  'chimes': {'CHIME-01-ID': True,
                                             'traditionalChime': True}},
                   'sipCallActive': False,
                   'smartTracking': False,
                   'smartZoom': {'bottomrightx': 0,
                                 'bottomrighty': 0,
                                 'topleftx': 0,
                                 'toplefty': 0},
                   'speaker': {'mute': False, 'volume': 100},
                   'state': 'idle',
                   'streamingMode': 'eventBased',
                   'swVersion': '1.9.1.0_8_9eedd22_ceefa49',
                   'timeSynchState': 'synchronized',
                   'timeZone': 'COT5',
                   'traditionalChime': False,
                   'traditionalChimeDuration': 320,
                   'traditionalChimeType': 'none',
                   'updateAvailable': None,
                   'updateCountryCode': 'unknown',
                   'videoMode': 'wide',
                   'voiceMailEnabled': False,
                   'zoom': {'bottomrightx': 1536,
                            'bottomrighty': 1536,
                            'topleftx': 0,
                            'toplefty': 0}},
    'state': 'provisioned',
    'states': {'activeMode': 'mode2',
               'motionStart': {'enabled': True,
                               'pushNotification': {'enabled': True},
                               'recordVideo': {'enabled': True,
                                               'fixedTime': {'duration': 10},
                                               'stopCondition': 'motionStop'},
                               'sensitivity': 45},
               'override': False,
               'schemaVersion': 1},
    'uniqueId': 'DOOR-BELL-01-UNIQUE-ID',
    'userId': 'USER-ID',
    'userRole': 'ADMIN',
    'xCloudId': 'DOOR-BELL-01-XCLOUD-ID'
}

DOOR_BELL_02 = {
    'allowedMqttTopics': ['d/BASE-STATION-02-XCLOUD-ID/out/doorbells/DOOR-BELL-02-ID/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/wifi/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/subscriptions/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/audioPlayback/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/modes/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/basestation/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/siren/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/devices/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/storage/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/schedule/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/diagnostics/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/automationRevisionUpdate/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/audio/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/activeAutomations/#',
                          'd/BASE-STATION-02-XCLOUD-ID/out/lte/#'],
    'dateCreated': 1735325442825,
    'deviceId': 'DOOR-BELL-02-ID',
    'deviceName': 'Door Bell 02',
    'deviceType': 'doorbell',
    'displayOrder': 0,
    'interfaceSchemaVer': '1',
    'interfaceVersion': 'i003',
    'lastImageUploaded': 'true',
    'lastModified': 1741180935446,
    'mediaObjectCount': 0,
    'modelId': 'AAD1001',
    'owner': {'firstName': 'USER-NAME',
              'lastName': 'USER-LAST-NAME',
              'ownerId': 'OWNER-ID'},
    'parentId': 'BASE-STATION-02-ID',
    'properties': {},
    'state': 'provisioned',
    'uniqueId': 'DOOR-BELL-02-UNIQUE-ID',
    'userId': 'USER-ID',
    'userRole': 'ADMIN',
    'xCloudId': 'BASE-STATION-02-XCLOUD-ID'
}

DOOR_BELL_02_UPDATES = {
    'activityState': 'idle',
    'batteryLevel': 50,
    'blockNotifications': {'block': False,
                           'duration': 0,
                           'endTime': 0},
    'chimes': {'CHIME-01-ID': {'trackId': 'TRACK-01-ID',
                               'volume': 90}},
    'connectionState': 'available',
    'hwVersion': '1.2',
    'idleLedEnable': True,
    'interfaceVersion': 1,
    'liveFeed': True,
    'mic': {'mute': False,
            'volume': 0},
    'modelId': 'AAD1001',
    'motion': {'sensitivity': 5},
    'motionSetupModeEnabled': False,
    'motionSetupModeSensitivity': 80,
    'name': '',
    'olsonTimeZone': 'America/New_York',
    'privacyActive': False,
    'serialNumber': 'DOOR-BELL-02-ID',
    'signalStrength': 3,
    'silentMode': {},
    'sipCallActive': False,
    'speaker': {'mute': False,
                'volume': 100},
    'states': {'motionStart': {'enabled': False,
                               'pushNotification': {'enabled': False}}},
    'swVersion': '1.2.0.0_320_401',
    'traditionalChime': True,
    'updateAvailable': None,
    'voiceMailEnabled': True
}
