#!/usr/bin/env python
#

import logging
import os
import sys

# for examples, import relative to starting path
sys.path.append('.')
import pyaarlo

# set these from the environment to log in
USERNAME = os.environ.get('ARLO_USERNAME', 'test.login@gmail.com')
PASSWORD = os.environ.get('ARLO_PASSWORD', 'test-password')

# set up logging, change INFO to DEBUG for a *lot* more information
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
_LOGGER = logging.getLogger('pyaarlo')

# log in
# add `verbose_debug=True` to enable even more debugging
# add `dump=True` to enable event stream packet dumps
arlo = pyaarlo.PyArlo(username=USERNAME, password=PASSWORD,
                      tfa_type='SMS', tfa_source='console',
                      save_state=False, dump=False, storage_dir='aarlo', verbose_debug=True)

print('list bases')
for base in arlo.base_stations:
    print("base: name={},device_id={},state={}".format(base.name, base.device_id, base.state))

print('list cameras')
for camera in arlo.cameras:
    print("camera: name={},device_id={},state={}".format(camera.name, camera.device_id, camera.state))

print('list doorbells')
for doorbell in arlo.doorbells:
    print("doorbell: name={},device_id={},state={}".format(doorbell.name, doorbell.device_id, doorbell.state))

print('list lights')
for light in arlo.lights:
    print("light: name={},device_id={},state={}".format(light.name, light.device_id, light.state))
