#!/usr/bin/env python
#

import logging
import os
import sys
import time

# for examples add pyaarlo install path
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
import pyaarlo

# set these from the environment to log in
USERNAME = os.environ.get('ARLO_USERNAME', 'test.login@gmail.com')
PASSWORD = os.environ.get('ARLO_PASSWORD', 'test-password')

# set up logging, change INFO to DEBUG for a *lot* more information
logging.basicConfig(level=logging.DEBUG,
                    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
_LOGGER = logging.getLogger('pyaarlo')


class Arlo2FATest:
    """ 2FA authentication via console.
    Accepts input from console and returns that for 2FA.
    """

    def __init__(self):
        pass

    def start(self):
        _LOGGER.debug('2fa-cconsole: starting')
        return True

    def get(self):
        _LOGGER.debug('2fa-cconsole: checking')
        return input('Custom Enter Code: ')

    def stop(self):
        _LOGGER.debug('2fa-cconsole: stopping')


# log in
# add `verbose_debug=True` to enable even more debugging
# add `dump=True` to enable event stream packet dumps
arlo = pyaarlo.PyArlo(username=USERNAME, password=PASSWORD,
                      tfa_type='SMS', tfa_source=Arlo2FATest(),
                      save_state=False, dump=False, storage_dir='aarlo', verbose_debug=True)

time.sleep(60)
