#!/usr/bin/env python

import os
import sys

# for examples add pyaarlo install path
sys.path.append(os.path.dirname(os.path.dirname(os.path.realpath(__file__))))
from pyaarlo.main import main_func

main_func()
